src/App.tsx
> [!NOTE]
- Close #26 
> [!NOTE]
```typescript
const { role } = useAuthStore();
```
위 변수를 사용하지 않아 ci 과정에서 에러가 발생했습니다.
해당 라인을 주석처리했습니다.
> [!NOTE]
> [!NOTE]
```text
```
=> fix(#26): 사용하지 않는 role 변수를 주석처리함

src/App.tsx, src/pages/Login/index.tsx, src/styles/custom-color.css
> [!NOTE]
- Close #20
> [!NOTE]
```text
공통 로그인 페이지 구현
```
> [!NOTE]
> [!NOTE]
```text
우선 기능 구현에 초점 맞췄고 리팩토링 거쳐서 컴포넌트 분리해야 될 거 같아요
```
=> feat(#20): 공통 로그인 페이지 구현

src/App.tsx, src/components/ApplicationForm/index.tsx, src/components/CommonCard/index.tsx, src/components/SaveButton/index.tsx, src/components/TestCategory/index.tsx, src/components/TestDate/index.tsx, src/components/TestLevel/index.tsx, src/components/TestScore/index.tsx, src/components/TestScoreCertification/index.tsx, src/pages/SwTestInputResult/index.tsx, src/pages/SwTestRequest/index.tsx
> [!NOTE]
- Close #21 #22 
> [!NOTE]
```text
- SW 역량 테스트 결과 입력 페이지 구현
```
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#21, #22): SW 역량 테스트 페이지 구현

src/store/auth.ts
> [!NOTE]
- Close #36 
> [!NOTE]
사용하지 않는 변수로 인해 배포가 안되어서 해당 변수를 제거했습니다.
> [!NOTE]
> [!NOTE]
```text
```
=> fix(#36): 미사용 변수 제거

src/pages/Student/Internship/EnterResult.tsx
> [!NOTE]
- Close #24 
> [!NOTE]
```text
인턴십 결과 입력 페이지 구현
```
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#31): 인턴십 결과 입력 페이지 구현

src/config/navigation.ts, src/pages/student/scholarship/swExpert/index.tsx
> [!NOTE]
- Close #28 
> [!NOTE]
```text
-  장학금 페이지를 구현하였습니다.
-  각각의 데이터를 넘겨줄 수 있도록 구현하였습니다.
-  저장 버튼을 눌렀을 때 각각의 데이터에 대한 유효성 검사가 진행됩니다.
```
> [!NOTE]
> [!NOTE]
[참고](https://jobda.kr/solidkpi/student/sw_expert_add.html)
```text
일단은 기능 구현과 UI 구현에 초점을 두었습니다.
```
=> feat(#28): SW EXPERT 장학금 페이지 구현

src/config/navigation.ts, src/pages/Student/SwTest/SwTestApplication/index.tsx, src/pages/Student/SwTest/SwTestEnterResult/index.tsx, src/routes/StudentRoutes.tsx
> [!NOTE]
- Close #38
> [!NOTE]
```text
sw 역량 테스트, sw expert 라우팅 추가
```
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#38): sw 역량 테스트, sw expert 라우팅 추가

src/routes/StudentRoutes.tsx
> [!NOTE]
- Close #40
> [!NOTE]
```text
navigation 경로 수정
```
> [!NOTE]
> [!NOTE]
```text
```
=> fix(#40): navigation 경로 수정

src/pages/Student/scholarship/SwSupport/index.tsx, src/pages/student/scholarship/swExpert/index.tsx, src/routes/StudentRoutes.tsx
> [!NOTE]
- Close #34 
> [!NOTE]
```text
-  SW 서포터즈 장학금 페이지를 구현하였습니다.
-  각각의 데이터를 넘겨줄 수 있도록 구현하였습니다.
-  저장 버튼을 눌렀을 때 각각의 데이터에 대한 유효성 검사가 진행됩니다.
```
> [!NOTE]
> [!NOTE]
```text
SW expert 페이지와 중복되는 컴포넌트들이 많아서 재사용하였습니다.
```
=> feat(#34): SW 서포터즈 장학금 페이지 구현

src/pages/Student/scholarship/SwSupport/index.tsx, src/pages/Student/scholarship/swExpert/index.tsx, src/pages/student/scholarship/swExpert/index.tsx
> [!NOTE]
- Close #45 
> [!NOTE]
```text
import 오류 수정
```
> [!NOTE]
> [!NOTE]
```text
```
=> fix(#45): import 오류 수정

src/components/Card/Title.tsx, src/components/Layout/index.tsx, src/pages/Student/Internship/Application.tsx, src/pages/Student/Internship/EnterResult.tsx
> [!NOTE]
- Close #52 
> [!NOTE]
- 각 페이지의 큰 제목을 나타내는 Title의 레이아웃을 수정했습니다.
> [!NOTE]
> [!NOTE]
```text
```
=> refactor(#52): 각 화면의 제목 디자인을 수정한다.

src/components/ApplicationForm/index.tsx, src/components/AvatarDropdownMenu/index.tsx, src/components/CommonCard/index.tsx, src/components/Header/index.tsx, src/components/Layout/index.tsx, src/components/MiniHeader/index.tsx, src/components/Sidebar/index.tsx, src/components/TestCategory/index.tsx, src/components/TestDate/index.tsx, src/components/TestLevel/index.tsx, src/components/TestScore/index.tsx, src/components/TestScoreCertification/index.tsx, src/styles/custom-color.css
> [!NOTE]
- Close #54 
> [!NOTE]
```text
배경 색상 변경
```
> [!NOTE]
> [!NOTE]
```text
hover 시 색상, border 색상 추후에 변경해야 합니다
```
=> refactor(background): 색상 변경

src/components/ApplicationForm/index.tsx, src/components/AvatarDropdownMenu/index.tsx, src/components/Card/Title.tsx, src/components/CommonCard/index.tsx, src/components/Header/index.tsx, src/components/MiniHeader/index.tsx, src/components/SaveButton/index.tsx, src/components/Sidebar/index.tsx, src/components/TestCategory/index.tsx, src/components/TestDate/index.tsx, src/components/TestLevel/index.tsx, src/components/TestScore/index.tsx, src/components/TestScoreCertification/index.tsx, src/pages/404/NotFound.module.css, src/pages/404/index.tsx, src/pages/500/InternalError.module.css, src/pages/500/index.tsx, src/pages/Student/Internship/Application.tsx, src/pages/Student/Internship/EnterResult.tsx, src/pages/Student/StudentHome/index.tsx, src/pages/Student/SwTest/SwTestApplication/index.tsx, src/pages/Student/SwTest/SwTestEnterResult/index.tsx, src/pages/Student/scholarship/SwSupport/index.tsx, src/pages/Student/scholarship/swExpert/index.tsx, src/store/auth.ts, src/styles/custom-color.css, src/styles/scrollbar.css
> [!NOTE]
- Close #56 
> [!NOTE]
```text
UI 수정
```
> [!NOTE]
> [!NOTE]
```text
스크롤바 천천히 사라지고, 천천히 보여지게 하려 했는데 잘 안돼서 보류하겠습니다
```
=> refactor(#56): UI 수정

src/config/navigation.ts, src/pages/Student/SwTalent/ CompetitionContest/index.tsx, src/pages/Student/SwTalent/ Thesis/index.tsx, src/routes/StudentRoutes.tsx
> [!NOTE]
- Close #59
> [!NOTE]
```text
SW 인재(경진대회/공모전, 논문) 페이지 생성
```
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#59): SW 인재(경진대회/공모전, 논문) 페이지 생성

src/pages/Student/scholarship/SwSupport/index.tsx, src/pages/Student/scholarship/swExpert/index.tsx
> [!NOTE]
- Close #64 
> [!NOTE]
```text
- UI 순서 조정
- UI 크기 조정
```
> [!NOTE]
> [!NOTE]
```text
```
=> refactor(#64): UI 순서 조정

src/pages/Student/Internship/Application.tsx, src/pages/Student/Internship/EnterResult.tsx, src/pages/Student/StudentHome/index.tsx, src/styles/color.ts
> [!NOTE]
- Close #58 
> [!NOTE]
위 화면을 구현현했습니다. 
초기 학생이 데이터를 입력하지 않은 상태일 경우에만 보여지는 화면입니다.
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#58) 학생 홈 화면 구현

src/pages/Student/scholarship/SwSupport/index.tsx, src/pages/Student/scholarship/swExpert/index.tsx
> [!NOTE]
- Close #70 
> [!NOTE]
```text
기본정보 입력 칸에 학생 기본정보를 불러와서 readOnly로 고정하였습니다.
```
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#70): 학생 기본 정보 불러오기

package-lock.json, src/config/navigation.ts, src/pages/Student/scholarship/sw-convergence/Index.tsx, src/pages/Student/sw-convergence/Index.tsx, src/routes/StudentRoutes.tsx
> [!NOTE]
- Close #66
> [!NOTE]
```
w 융합 페이지 생성
//다만 dku 융합부분이 정확히 뭘 위한건지 왜 필요한건지에대한 의문이 남아있습니다. 관련자료도 찾아보고 고덕환 이사님 화면 설계를 봐도 어떤 의미를 가지는 페이지인지 정확하게 모르겠지만 우선 화면 설계서대로 만들어보았습니다.
```
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#66): sw 융합페이지 생성

src/App.tsx, src/config/navigation.ts, src/pages/Professor/SolidCloud/index.tsx, src/routes/ProfessorRoutes.tsx, src/store/auth.ts
> [!NOTE]
- Close #76 
> [!NOTE]
Role이 PROFESSOR일 때 라우터를 생성했습니다.
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#76): 교수 전용 Routes 생성

package-lock.json, package.json, src/components/ChartCard/index.tsx, src/config/navigation.ts, src/pages/Professor/Internship/index.tsx, src/routes/ProfessorRoutes.tsx, src/store/internship.ts
> [!NOTE]
- Close #74
> [!NOTE]
```text
professor internship page 구현
```
> [!NOTE]
> [!NOTE]
```text
데이터를 분리했는데 저대로 둬도 괜찮을지 궁금합니다
```
=> feat(#74): professor internship page 구현

src/pages/Student/SwTalent/ Thesis/index.tsx
> [!NOTE]
- Close #96 
> [!NOTE]
```text
import 되었지만 사용하지 않는 것들을 제거했습니다.
```
> [!NOTE]
> [!NOTE]
```text
```
=> fix(#96): 사용하지 않는 Import를 제거한다.

src/config/navigation.ts, src/pages/Professor/IndustryAcademiaProject/index.tsx, src/routes/ProfessorRoutes.tsx, src/store/industryAcademiaProject.ts
> [!NOTE]
- Close #79 
> [!NOTE]
```
교수 산합협력 프로젝트 참여율 페이지 생성
```
> [!NOTE]
> [!NOTE]
```
```
=> feat(#79): 교수 산학협력 프로젝트 참여율 페이지 생성

src/config/navigation.ts, src/pages/Professor/CompetitionContest/index.tsx, src/routes/ProfessorRoutes.tsx, src/store/auth.ts, src/store/competitionContest.ts
> [!NOTE]
- Close #78 
> [!NOTE]
```
교수 경진대회 페이지 생성
```
> [!NOTE]
> [!NOTE]
```
규원님 코드 참고하여 작성하였습니다!
```
=> feat(#78): 교수 경진대회 페이지 생성

package-lock.json, src/pages/Professor/NumOfStudent/index.tsx, src/routes/ProfessorRoutes.tsx
> [!NOTE]
- Close #83 
> [!NOTE]
```text
professor 교원 1인당 학생수 페이지 생성
```
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#83):professor 교원 1인당 학생수 페이지 생성

package-lock.json, package.json, src/App.tsx, src/components/AddButton/index.tsx, src/components/FileTable/index.tsx, src/components/Pagination/index.tsx, src/components/SearchBar/index.tsx, src/config/navigation.ts, src/pages/Professor/FileStore/index.tsx, src/routes/SuperAdminRoutes.tsx, src/store/auth.ts, src/store/fileStore.ts, src/styles/custom-color.css
> [!NOTE]
- Close #94
> [!NOTE]
```text
super admin 양식함 관리 페이지 구현
```
> [!NOTE]
> [!NOTE]
```text
super admin 라우터 추가했고 기본 role 상태 super admin 으로 변경했습니다
pagination 은 디테일 더 잡아야 될 거 같아요
```
=> feat(#94): super admin 양식함 관리 페이지 구현

src/config/navigation.ts, src/routes/SuperAdminRoutes.tsx
> [!NOTE]
- Close #104 
> [!NOTE]
```text
SuperAdmin 대시보드 컴포넌트 재사용
```
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#104): SuperAdmin 대시보드 컴포넌트 재사용

src/config/navigation.ts, src/pages/Management/Professor/index.tsx, src/routes/AdminRoutes.tsx, src/routes/ProfessorRoutes.tsx, src/routes/SuperAdminRoutes.tsx
> [!NOTE]
- Close #105 
> [!NOTE]
```text
교수 관리 페이지 구현
```
> [!NOTE]
> [!NOTE]
```text
테이블 색상이 검정으로 안바뀌네요...
```
=> feat(#105): 교수 관리 페이지 구현

src/components/StudentSearchBar/index.tsx, src/components/StudentTable/index.tsx, src/config/navigation.ts, src/pages/Management/studuentlist/index.tsx, src/routes/SuperAdminRoutes.tsx, src/store/studentStore.ts
> [!NOTE]
- Close #109 
> [!NOTE]
```text
슈퍼 관리자 학생 관리 페이지 생성
```
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#109): 슈퍼관리자  학생 관리 페이지 생성

src/components/AddButton/index.tsx, src/config/navigation.ts, src/pages/Management/FileStore/index.tsx, src/pages/Management/FileStoreAdd/index.tsx, src/routes/AdminRoutes.tsx, src/routes/SuperAdminRoutes.tsx
> [!NOTE]
- Close #119
> [!NOTE]
- file store add page 구현
> [!NOTE]
> [!NOTE]
```text
```
=> feat(#119): file store add page 구현

src/pages/SuperAdmin/Companies/AddButton/index.tsx, src/pages/SuperAdmin/Companies/AddCompany/index.tsx, src/pages/SuperAdmin/Companies/index.tsx, src/routes/SuperAdminRoutes.tsx
> [!NOTE]
- Close #121 
> [!NOTE]
```text
업체 추가 페이지 구현
```
> [!NOTE]
```text
```
=> feat(#121): 업체 추가 페이지 구현 

src/components/ItemTable/index.tsx, src/config/navigation.ts, src/pages/Management/Item/AddButton/index.tsx, src/pages/Management/Item/AddItem/index.tsx, src/pages/Management/Item/SearchBar/index.tsx, src/pages/Management/Item/index.tsx, src/routes/AdminRoutes.tsx, src/routes/SuperAdminRoutes.tsx, src/store/item.ts
> [!NOTE]
- Close #113 
> [!NOTE]
```
수퍼 관리자의 아이템 관리 페이지 구현
```
> [!NOTE]
> [!NOTE]
```
```
=> feat(#113): 수퍼 관리자 아이템 관리 페이지 생성
